-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."join_request" add column "status" integer
--  not null default '1';
