-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."join_request" add column "state" varchar
--  not null default 'pending';
