apiVersion: v1
kind: Service
metadata:
  labels:
    app: protonaffiliate-hasura
  name: protonaffiliate-hasura
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: hasura
      protocol: TCP
  selector:
    app: protonaffiliate-hasura
