apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: protonaffiliate-postgres
    version: ${VERSION}
  name: protonaffiliate-postgres
spec:
  serviceName: protonaffiliate-postgres
  replicas: 1
  selector:
    matchLabels:
      app: protonaffiliate-postgres
      version: ${VERSION}
  template:
    metadata:
      labels:
        app: protonaffiliate-postgres
        version: ${VERSION}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - image: postgres:11.5-alpine
          imagePullPolicy: 'Always'
          name: protonaffiliate-postgres
          envFrom:
            - configMapRef:
                name: protonaffiliate-postgres-config
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres
              subPath: postgres
  volumeClaimTemplates:
    - metadata:
        name: postgres
      spec:
        accessModes: ['ReadWriteOnce']
        storageClassName: dashboard-storage
        resources:
          requests:
            storage: 100Gi
