name: Build images from latest dev branch

on:
  push:
    branches:
      - dev

jobs:
  create-dev-image:
    name:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@0.0.1

      - name: Log in to docker registry
        run: |
          echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login \
            --username ${{ secrets.DOCKER_HUB_USER }} \
            --password-stdin

      - name: Build new images and push
        run: |
          make \
            build-docker-images \
            push-docker-images
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          # webapp
          REACT_APP_VERSION: ${{ github.ref }}
          REACT_APP_NAME: 'proton_affiliate'
          REACT_APP_TITLE: 'Proton Affiliate'
          REACT_APP_LOGO: 'https://raw.githubusercontent.com/eoscostarica/design-assets/master/logos/eosCR/fullColor-vertiall-transparent-white.png'
          REACT_APP_FOOTER_LINKS: '[]'
          REACT_APP_UAL_APP_NAME: 'Proton Affiliate'
          REACT_APP_UAL_API_PROTOCOL: 'https'
          REACT_APP_UAL_API_HOST: 'proton-testnet.eosio.cr'
          REACT_APP_UAL_API_PORT: '443'
          REACT_APP_UAL_CHAIN_ID: '71ee83bcf52142d61019d95f9cc5427ba6a0d7ff8accd9e2088ae2abeaf3d3dd'
          REACT_APP_HASURA_URL: ${{ secrets.REACT_APP_HASURA_URL }}

      - name: Build kubernetes files
        id: build_kubernetes_files
        run: |
          make \
            build-kubernetes
        env:
          # general
          NAMESPACE: affiliateproton
          INGRESS_HOST: testnet-affiliateproton.io
          # postgres
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          # hapi
          HAPI_SERVER_PORT: 9090
          HAPI_SERVER_ADDRESS: 0.0.0.0
          HAPI_NETWORK_API: 'https://proton-testnet.eosio.cr'
          HAPI_NETWORK_CHAIN_ID: '71ee83bcf52142d61019d95f9cc5427ba6a0d7ff8accd9e2088ae2abeaf3d3dd'
          HAPI_NETWORK_CREATOR_ACCOUNT: ${{ secrets.HAPI_NETWORK_CREATOR_ACCOUNT }}
          HAPI_NETWORK_CREATOR_PASSWORD: ${{ secrets.HAPI_NETWORK_CREATOR_PASSWORD }}
          HAPI_NETWORK_WALLET: ${{ secrets.HAPI_NETWORK_WALLET }}
          HAPI_HASURA_URL: ${{ secrets.HAPI_HASURA_URL }}
          HAPI_HASURA_ADMIN_SECRET: ${{ secrets.HAPI_HASURA_ADMIN_SECRET }}
          HAPI_AFFILIATE_ACCOUNT: ${{ secrets.HAPI_AFFILIATE_ACCOUNT }}
          HAPI_AFFILIATE_PASSWORD: ${{ secrets.HAPI_AFFILIATE_PASSWORD }}
          # hasura
          HASURA_GRAPHQL_ENABLE_CONSOLE: true
          HASURA_GRAPHQL_DATABASE_URL: ${{ secrets.HASURA_GRAPHQL_DATABASE_URL }}
          HASURA_GRAPHQL_ADMIN_SECRET: ${{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}
          HASURA_GRAPHQL_UNAUTHORIZED_ROLE: : ${{ secrets.HASURA_GRAPHQL_UNAUTHORIZED_ROLE }}

      - name: Deploy kubernetes files
        uses: Consensys/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply -f build_k8s -n affiliateproton
